github:
  username: ${{ secrets.GITHUB_USERNAME }}
  token:    ${{ secrets.PAT }}

codeowners:
- path:  "*"
  owner: "@initializ-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/initializbuildpacks/datadog"]
  register:       true
  registry_token: ${{ secrets.PAT }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.INITIALIZ_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.INITIALIZ_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   datadog-agent-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo1.maven.org/maven2
    group_id:    com.datadoghq
    artifact_id: dd-java-agent
- id:   datadog-agent-nodejs
  uses: docker://ghcr.io/paketo-buildpacks/actions/npm-dependency:main
  with:
    package: dd-trace
